import { useEffect, useRef, useState } from 'react'
import { ChevronDown, Database, Eye, EyeOff, Layers3, LogOut, Map as MapIcon, Palette, PanelRightClose, Settings, Users, Wifi, WifiOff, X } from 'lucide-react'
import { api, authToken } from '../lib/api'
import { localRepository } from '../lib/localRepository'
import { useAppStore } from '../store'
import type { Dataset } from '../types'
import { DataPanel } from './DataPanel'
import { IdentifyCard } from './IdentifyCard'
import { LayerPanel } from './LayerPanel'
import { MapCanvas, type MapCanvasHandle } from './MapCanvas'
import { SettingsPanel } from './SettingsPanel'
import { StylePanel } from './StylePanel'
import { TeamPanel } from './TeamPanel'
interface Props { onExit: () => void }
const panelInfo = { layers: { label: '图层', icon: Layers3 }, data: { label: '数据', icon: Database }, style: { label: '制图', icon: Palette }, team: { label: '成员', icon: Users }, settings: { label: '设置', icon: Settings } } as const
export function AppShell({ onExit }: Props) {
  const mapRef = useRef<MapCanvasHandle>(null), user = useAppStore((state) => state.user), workspaces = useAppStore((state) => state.workspaces), workspace = useAppStore((state) => state.workspace), mode = useAppStore((state) => state.mode), layers = useAppStore((state) => state.layers), activePanel = useAppStore((state) => state.activePanel), busy = useAppStore((state) => state.busy), notice = useAppStore((state) => state.notice)
  const setWorkspace = useAppStore((state) => state.setWorkspace), setDatasets = useAppStore((state) => state.setDatasets), setPanel = useAppStore((state) => state.setPanel), setActiveLayer = useAppStore((state) => state.setActiveLayer), toggleLayer = useAppStore((state) => state.toggleLayer), notify = useAppStore((state) => state.notify)
  const [panelWidth, setPanelWidth] = useState(Number(localStorage.getItem('resilience_panel_width')) || 390), [online, setOnline] = useState(navigator.onLine), dragging = useRef(false)
  useEffect(() => { void (async () => { try { setDatasets(mode === 'local' ? await localRepository.list() : workspace ? await api.datasets(workspace.id) : []) } catch (error) { notify({ type: 'error', message: error instanceof Error ? error.message : '数据加载失败' }) } })() }, [mode, notify, setDatasets, workspace])
  useEffect(() => { const on = () => setOnline(true), off = () => setOnline(false); window.addEventListener('online', on); window.addEventListener('offline', off); return () => { window.removeEventListener('online', on); window.removeEventListener('offline', off) } }, [])
  useEffect(() => { const move = (event: MouseEvent) => { if (!dragging.current) return; const width = Math.max(330, Math.min(560, window.innerWidth - event.clientX)); setPanelWidth(width); localStorage.setItem('resilience_panel_width', String(width)); window.dispatchEvent(new Event('resize')) }; const up = () => { dragging.current = false; document.body.classList.remove('resizing') }; window.addEventListener('mousemove', move); window.addEventListener('mouseup', up); return () => { window.removeEventListener('mousemove', move); window.removeEventListener('mouseup', up) } }, [])
  useEffect(() => { if (!notice) return; const timer = window.setTimeout(() => notify(null), 3600); return () => clearTimeout(timer) }, [notice, notify])
  useEffect(() => { const key = (event: KeyboardEvent) => { if (!event.ctrlKey || ['INPUT', 'TEXTAREA'].includes((event.target as HTMLElement).tagName)) return; const value = event.key.toLowerCase(); if (value === 'l') { event.preventDefault(); setPanel('layers') } if (value === 'd') { event.preventDefault(); setPanel('data') } if (value === 'u') { event.preventDefault(); setPanel('data'); setTimeout(() => document.querySelector<HTMLInputElement>('.upload-zone input')?.click(), 100) } if (value === 'm') { event.preventDefault(); const next = document.documentElement.dataset.theme === 'light' ? 'dark' : 'light'; document.documentElement.dataset.theme = next; localStorage.setItem('resilience_theme', next) } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key) }, [setPanel])
  function exit() { authToken.clear(); onExit() }
  const currentPanel = activePanel ? panelInfo[activePanel] : null
  const panelDescription = activePanel === 'style' ? '图层符号与渲染属性' : activePanel === 'data' ? '团队与本地空间数据' : activePanel === 'layers' ? '当前地图中的工作图层' : activePanel === 'team' ? '共享权限与协作成员' : '工作台偏好与快捷键'
  return <div className="app-shell"><header className="topbar"><div className="topbar-brand"><span className="brand-mark small"><i /><i /><i /></span><div><b>韧性云图</b><span>RESILIENCE ATLAS</span></div></div><div className="topbar-divider" /><button className="workspace-switch" disabled={!workspaces.length} onClick={() => { const index = workspaces.findIndex((item) => item.id === workspace?.id); if (workspaces.length > 1) setWorkspace(workspaces[(index + 1) % workspaces.length]) }}><span className="workspace-icon"><MapIcon /></span><span><small>当前工作空间</small><b>{workspace?.name || '本地工作台'}</b></span>{workspaces.length > 1 && <ChevronDown />}</button><div className="topbar-spacer" /><span className={`connection ${online ? '' : 'offline'}`}>{online ? <Wifi /> : <WifiOff />}{mode === 'local' ? '本地模式' : online ? '团队已连接' : '网络已断开'}</span><nav className="top-actions">{(['layers', 'data', 'team', 'settings'] as const).map((key) => { const Icon = panelInfo[key].icon; return <button key={key} className={activePanel === key ? 'active' : ''} onClick={() => setPanel(activePanel === key ? null : key)} title={panelInfo[key].label}><Icon /><span>{panelInfo[key].label}</span></button> })}</nav><button className="user-menu" title="退出" onClick={exit}><span>{user?.display_name.slice(0, 1).toUpperCase() || '本'}</span><div><b>{user?.display_name || '本地用户'}</b><small>{workspace?.role || '仅此设备'}</small></div><LogOut /></button></header>
    <main className="workspace-main"><MapCanvas ref={mapRef} /><aside className="floating-toc"><header><span><Layers3 />图层控制</span><b>{layers.length}</b></header>{!layers.length ? <p>暂无加载图层</p> : <div>{layers.map((item) => <button key={item.dataset.id} onClick={() => { setActiveLayer(item.dataset.id); setPanel('style') }}><i className={item.dataset.type} style={{ background: item.dataset.type === 'vector' ? item.style.singleColor : undefined }} /><span>{item.dataset.name}</span><em onClick={(event) => { event.stopPropagation(); toggleLayer(item.dataset.id) }}>{item.visible ? <Eye /> : <EyeOff />}</em></button>)}</div>}</aside><IdentifyCard />
      {activePanel && currentPanel && <><div className="resize-handle" style={{ right: panelWidth }} onMouseDown={() => { dragging.current = true; document.body.classList.add('resizing') }} /><aside className="right-panel" style={{ width: panelWidth }}><header className="panel-header"><div><span>{<currentPanel.icon />}</span><div><h2>{currentPanel.label}</h2><p>{panelDescription}</p></div></div><button onClick={() => setPanel(null)} title="收起面板"><PanelRightClose /></button></header>{activePanel === 'layers' && <LayerPanel onZoom={(dataset: Dataset) => mapRef.current?.zoomToDataset(dataset)} />}{activePanel === 'data' && <DataPanel />}{activePanel === 'style' && <StylePanel />}{activePanel === 'team' && <TeamPanel />}{activePanel === 'settings' && <SettingsPanel />}</aside></>}
    </main>{notice && <div className={`toast ${notice.type}`}><span>{notice.message}</span><button onClick={() => notify(null)}><X /></button></div>}{busy && <div className="busy-overlay"><div className="loader-orbit"><i /><i /><i /></div><b>{busy}</b><span>正在解析投影、构建空间索引并生成预览</span></div>}</div>
}
