import { Check, ChevronLeft, Palette, RotateCcw, Save } from 'lucide-react'
import { api } from '../lib/api'
import { RAMPS, ramp, rampCss } from '../lib/ramps'
import { defaultStyle, useAppStore } from '../store'
import type { LayerStyle } from '../types'
function ColorRamp({ value, onChange }: { value: string; onChange: (name: string) => void }) { return <div className="ramp-options">{RAMPS.map((item) => <button key={item.name} className={value === item.name ? 'active' : ''} onClick={() => onChange(item.name)}><span>{item.name}</span><i style={{ background: rampCss(item.name) }} />{value === item.name && <Check size={14} />}</button>)}</div> }
function Legend({ style, type, field }: { style: LayerStyle; type: 'vector' | 'raster'; field: string | null }) {
  if (type === 'vector' && !field) return <div className="legend-list"><div><i style={{ background: style.singleColor, borderColor: style.outlineColor }} /><span>全部要素</span></div></div>
  if (type === 'raster' && style.rasterMode === 'continuous') return <div className="continuous-legend"><i style={{ background: rampCss(style.rampName) }} /><div><span>{style.min.toFixed(2)}</span><span>{style.max.toFixed(2)}</span></div></div>
  const scale = ramp(style.rampName); let previous: number | null = type === 'raster' ? style.min : null
  return <div className="legend-list">{style.breaks.map((boundary, index) => { const start = previous; previous = boundary; return <div key={`${boundary}-${index}`}><i style={{ background: scale(index / Math.max(1, style.classes - 1)).hex() }} /><span>{start == null ? `≤ ${boundary.toFixed(2)}` : `${start.toFixed(2)} – ${boundary.toFixed(2)}`}</span></div> })}</div>
}
export function StylePanel() {
  const activeId = useAppStore((state) => state.activeLayerId), layer = useAppStore((state) => state.layers.find((item) => item.dataset.id === activeId)), update = useAppStore((state) => state.updateLayerStyle), setPanel = useAppStore((state) => state.setPanel), notify = useAppStore((state) => state.notify)
  if (!layer) return <div className="panel-body"><div className="empty-state large"><Palette /><b>请选择图层</b><span>从图层面板选择一个图层后调整样式</span><button className="small-button" onClick={() => setPanel('layers')}>返回图层</button></div></div>
  const { dataset, style } = layer, numericFields = dataset.fields.filter((field) => field.type === 'number'), geometry = (dataset.geometry_type || '').toLowerCase(), kind = geometry.includes('line') ? 'line' : geometry.includes('point') ? 'point' : 'polygon', set = (patch: Partial<LayerStyle>) => update(dataset.id, patch)
  async function save() { if (dataset.local) return notify({ type: 'success', message: '本地样式已应用到当前地图' }); try { await api.patchDataset(dataset.id, { style }); notify({ type: 'success', message: '制图样式已保存到团队空间' }) } catch (error) { notify({ type: 'error', message: error instanceof Error ? error.message : '样式保存失败' }) } }
  return <div className="panel-body style-panel">
    <button className="back-link" onClick={() => setPanel('layers')}><ChevronLeft size={15} />返回图层列表</button><div className="style-layer-title"><span className={`file-kind ${dataset.type}`}><Palette /></span><div><h3>{dataset.name}</h3><p>{dataset.type === 'raster' ? '栅格 · GeoTIFF' : `矢量 · ${dataset.geometry_type || '混合类型'}`}</p></div></div>
    <section className="control-section"><div className="control-title"><b>基础显示</b><span>{Math.round(style.opacity * 100)}%</span></div><label className="range-row"><span>透明度</span><input type="range" min="0" max="1" step="0.05" value={style.opacity} onChange={(event) => set({ opacity: Number(event.target.value) })} /></label></section>
    {dataset.type === 'vector' ? <><section className="control-section"><div className="control-title"><b>数据驱动渲染</b><span>数值字段</span></div><label className="field-label">渲染字段<select value={style.field || ''} onChange={(event) => set({ field: event.target.value || null })}><option value="">单一符号</option>{numericFields.map((field) => <option key={field.name} value={field.name}>{field.name}</option>)}</select></label>{!numericFields.length && <p className="control-note">没有检测到数值字段，当前使用单一符号。</p>}</section>
      {!style.field ? <section className="control-section"><div className="control-title"><b>符号颜色</b></div><div className="color-controls"><label><span>{kind === 'line' ? '线颜色' : '填充颜色'}</span><input type="color" value={style.singleColor} onChange={(event) => set({ singleColor: event.target.value })} /><code>{style.singleColor}</code></label>{kind !== 'line' && <label><span>描边颜色</span><input type="color" value={style.outlineColor} onChange={(event) => set({ outlineColor: event.target.value })} /><code>{style.outlineColor}</code></label>}</div></section> : <><section className="control-section"><div className="control-title"><b>配色方案</b><span>{style.rampName}</span></div><ColorRamp value={style.rampName} onChange={(rampName) => set({ rampName })} /></section><section className="control-section"><div className="control-title"><b>分级数量</b><span>{style.classes} 级</span></div><input className="full-range" type="range" min="3" max="9" value={style.classes} onChange={(event) => set({ classes: Number(event.target.value) })} /></section></>}
      {kind === 'line' && <section className="control-section"><div className="control-title"><b>线宽</b><span>{style.weight.toFixed(1)} px</span></div><input className="full-range" type="range" min="0.5" max="10" step="0.5" value={style.weight} onChange={(event) => set({ weight: Number(event.target.value) })} /></section>}{kind === 'point' && <section className="control-section"><div className="control-title"><b>点大小</b><span>{style.radius} px</span></div><input className="full-range" type="range" min="2" max="18" value={style.radius} onChange={(event) => set({ radius: Number(event.target.value) })} /></section>}</> : <>
      <section className="control-section"><div className="control-title"><b>配色方案</b><span>{style.rampName}</span></div><ColorRamp value={style.rampName} onChange={(rampName) => set({ rampName })} /></section><section className="control-section"><div className="control-title"><b>渲染方式</b></div><div className="segmented"><button className={style.rasterMode === 'classified' ? 'active' : ''} onClick={() => set({ rasterMode: 'classified' })}>分段渲染</button><button className={style.rasterMode === 'continuous' ? 'active' : ''} onClick={() => set({ rasterMode: 'continuous' })}>连续渐变</button></div></section>
      {style.rasterMode === 'classified' && <section className="control-section"><div className="control-title"><b>分段规则</b><span>{style.classes} 级</span></div><label className="field-label">分类方法<select value={style.classify} onChange={(event) => set({ classify: event.target.value as LayerStyle['classify'] })}><option value="quantile">分位数</option><option value="equal">等距</option><option value="manual">手动阈值</option></select></label><input className="full-range" type="range" min="3" max="12" value={style.classes} onChange={(event) => set({ classes: Number(event.target.value) })} />{style.classify === 'manual' && <label className="field-label manual-field">阈值（逗号分隔）<textarea rows={3} value={style.manualBreaks} onChange={(event) => set({ manualBreaks: event.target.value })} placeholder="20, 40, 60, 80, 100" /></label>}</section>}<section className="control-section"><div className="control-title"><b>数值范围</b></div><div className="number-pair"><label>最小值<input type="number" value={style.min} onChange={(event) => set({ min: Number(event.target.value) })} /></label><label>最大值<input type="number" value={style.max} onChange={(event) => set({ max: Number(event.target.value) })} /></label></div></section></>}
    <section className="control-section"><div className="control-title"><b>实时图例</b><span>{style.field || (dataset.type === 'raster' ? '像元值' : '单一符号')}</span></div><Legend style={style} type={dataset.type} field={style.field} /></section><div className="style-actions"><button className="secondary-button" onClick={() => set(defaultStyle(dataset))}><RotateCcw size={15} />恢复默认</button><button className="primary-button" onClick={() => void save()}><Save size={15} />保存样式</button></div>
  </div>
}
